### ISSUE TITLE
rggen-vhdl generates APB interface when the protocol is specified as wishbone

### ISSUE THREAD

**Issue by m-kru** [rggen/rggen#216] opened 2024-07-12 12:07 UTC
`rggen-vhdl` generates APB interface when the protocol is specified as wishbone.

```yaml
bus_width: 32
address_width: 32
protocol: wishbone
```

```vhdl
entity Main is
  generic (
    ADDRESS_WIDTH: positive := 8;
    PRE_DECODE: boolean := false;
    BASE_ADDRESS: unsigned := x"0";
    ERROR_STATUS: boolean := false;
    INSERT_SLICER: boolean := false
  );
  port (
    i_clk: in std_logic;
    i_rst_n: in std_logic;
    i_psel: in std_logic;
    i_penable: in std_logic;
    i_paddr: in std_logic_vector(ADDRESS_WIDTH-1 downto 0);
    i_pprot: in std_logic_vector(2 downto 0);
    i_pwrite: in std_logic;
    i_pstrb: in std_logic_vector(3 downto 0);
    i_pwdata: in std_logic_vector(31 downto 0);
    o_pready: out std_logic;
    o_prdata: out std_logic_vector(31 downto 0);
    o_pslverr: out std_logic;
```

**Comment by taichi-ishitani** [comment] 2024-07-12 13:28
I was not able to reproduce this issue on my side.
I think you forgot to specify your config file.
Can you confirm that?

**Comment by m-kru** [comment] 2024-07-12 13:42
What does you `config.yaml` look like?

**Comment by taichi-ishitani** [comment] 2024-07-12 13:57
Same with the config file which you show.

```yaml
bus_width: 32
address_width: 32
protocol: wishbone
```

**Comment by m-kru** [comment] 2024-07-12 14:29
This snippet is a part of my register description file. I do not provide any config file.

**Comment by taichi-ishitani** [comment] 2024-07-12 14:42
You need to put these properties to your config file.

**Comment by m-kru** [comment] 2024-07-12 14:43
Why? Why do I need to duplicate this information?

**Comment by taichi-ishitani** [comment] 2024-07-12 14:44
You don't have to put them to your register map file.

**Comment by m-kru** [comment] 2024-07-12 14:47
If I put them there `rggen` doesn't issue any error or warning. However, they don't work. I feel confused.

**Comment by m-kru** [comment] 2024-07-13 16:06
https://github.com/rggen/rggen/issues/218

**Comment by m-kru** [comment] 2024-07-13 16:09
What version of rggen do you use? I use RgGen 0.33 and even if I put this data into the config file, I still get output files utilizing APB, not Wishbone.

**Comment by taichi-ishitani** [comment] 2024-07-14 01:13
I use 0.33.
Can you provide me your config file and execution command?

**Comment by m-kru** [comment] 2024-07-14 10:59
The source of the problem was lack of the `-c` argument.

```
rggen config.yaml --plugin rggen-vhdl bus.yaml 
```

Looks like rggen accepts invalid configuration in multiple places and simply silently moves on.

**Comment by taichi-ishitani** [comment] 2024-07-14 11:47
> Looks like rggen accepts invalid configuration in multiple places and simply silently moves on.

This will be fixed by #218 .

**Comment by taichi-ishitani** [comment] 2024-07-20 16:15
I released RgGen v0.33.3.
From this release, RgGen will report an error when unknown field is given like below.
![image](https://github.com/user-attachments/assets/d3fb2025-bc85-41f0-b72b-84b29dfb9a12)

**Closed by taichi-ishitani** 2024-07-20 16:15 UTC
